// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Notification.Infrastructure.Persistence;

#nullable disable

namespace Notification.Infrastructure.Persistence.Migrations;

[DbContext(typeof(NotificationDbContext))]
[Migration("20260829180000_UserNotifications")]
partial class UserNotifications
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("notification");

        modelBuilder.Entity("Notification.Domain.UserNotifications.UserNotification", builder =>
        {
            builder.Property<Guid>("Uuid").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("uuid");
            builder.Property<Guid>("UserUuid").HasColumnType("uuid").HasColumnName("user_uuid");
            builder.Property<string>("Kind").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("kind");
            builder.Property<string>("SubjectSignature").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("subject_signature");
            builder.Property<Guid>("SubjectUuid").HasColumnType("uuid").HasColumnName("subject_uuid");
            builder.Property<string>("SubjectKey").HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("subject_key");
            builder.Property<string>("TitleKey").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("title_key");
            builder.Property<string>("ParamsJson").IsRequired().HasColumnType("jsonb").HasColumnName("params");
            builder.Property<string>("GroupKey").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("group_key");
            builder.Property<Guid>("CorrelationId").HasColumnType("uuid").HasColumnName("correlation_id");
            builder.Property<string>("Link").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("link");
            builder.Property<int>("Severity").HasColumnType("integer").HasColumnName("severity");
            builder.Property<int>("OccurrenceCount").HasColumnType("integer").HasColumnName("occurrence_count");
            builder.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
            builder.Property<DateTimeOffset>("LastOccurredAt").HasColumnType("timestamp with time zone").HasColumnName("last_occurred_at");
            builder.Property<DateTimeOffset?>("SeenAt").HasColumnType("timestamp with time zone").HasColumnName("seen_at");
            builder.Property<DateTimeOffset?>("ReadAt").HasColumnType("timestamp with time zone").HasColumnName("read_at");
            builder.Property<DateTimeOffset?>("ExpireOn").HasColumnType("timestamp with time zone").HasColumnName("expire_on");
            builder.Property<uint>("xmin").IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().HasColumnType("xid").HasColumnName("xmin");
            builder.HasKey("Uuid").HasName("pk_user_notification");
            builder.HasIndex("UserUuid", "CreatedAt").IsDescending(false, true).HasDatabaseName("ix_user_notification_user_uuid_created_at");
            builder.HasIndex("UserUuid").HasDatabaseName("ix_user_notification_unread").HasFilter("read_at IS NULL");
            builder.HasIndex("UserUuid", "GroupKey").IsUnique().HasDatabaseName("ix_user_notification_active_group").HasFilter("group_key IS NOT NULL AND read_at IS NULL");
            builder.HasIndex("UserUuid", "Kind", "SubjectUuid", "CorrelationId").IsUnique().HasDatabaseName("ix_user_notification_ungrouped_dedup").HasFilter("group_key IS NULL");
            builder.ToTable("user_notification", "notification");
        });
    }
}
