<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../building-blocks/Erp.BuildingBlocks.Domain/Erp.BuildingBlocks.Domain.csproj" />
  </ItemGroup>

</Project>
