/**
 * Typesafe translation keys for the warranty scope.
 * Generated automatically from pl-PL.json.
 * Do not edit this file manually.
 */
export const WARRANTY_KEYS = {
    picker: {
      label: 'warranty.picker.label',
      placeholder: 'warranty.picker.placeholder',
      searchPlaceholder: 'warranty.picker.searchPlaceholder',
      empty: 'warranty.picker.empty',
    },
  } as const;
