/**
 * Typesafe translation keys for the taskManagement scope.
 * Generated automatically from pl-PL.json.
 * Do not edit this file manually.
 */
export const TASKMANAGEMENT_KEYS = {
    workflow: {
      states: {
        todo: 'taskManagement.workflow.states.todo',
        inProgress: 'taskManagement.workflow.states.inProgress',
        done: 'taskManagement.workflow.states.done',
      },
      transitions: {
        start: 'taskManagement.workflow.transitions.start',
        return: 'taskManagement.workflow.transitions.return',
        finish: 'taskManagement.workflow.transitions.finish',
        reopen: 'taskManagement.workflow.transitions.reopen',
        close: 'taskManagement.workflow.transitions.close',
        reopenToTodo: 'taskManagement.workflow.transitions.reopenToTodo',
      },
      categories: {
        todo: 'taskManagement.workflow.categories.todo',
        inProgress: 'taskManagement.workflow.categories.inProgress',
        done: 'taskManagement.workflow.categories.done',
      },
    },
    priority: {
      lowest: 'taskManagement.priority.lowest',
      low: 'taskManagement.priority.low',
      normal: 'taskManagement.priority.normal',
      high: 'taskManagement.priority.high',
      critical: 'taskManagement.priority.critical',
    },
    projectKind: {
      delivery: 'taskManagement.projectKind.delivery',
      intake: 'taskManagement.projectKind.intake',
    },
    projectMemberRole: {
      viewer: 'taskManagement.projectMemberRole.viewer',
      contributor: 'taskManagement.projectMemberRole.contributor',
      lead: 'taskManagement.projectMemberRole.lead',
    },
    fields: {
      storyPoints: 'taskManagement.fields.storyPoints',
      component: 'taskManagement.fields.component',
      fixVersion: 'taskManagement.fields.fixVersion',
      startedOn: 'taskManagement.fields.startedOn',
      reviewer: 'taskManagement.fields.reviewer',
      notes: 'taskManagement.fields.notes',
    },
    issueTypeCategory: {
      epic: 'taskManagement.issueTypeCategory.epic',
      standard: 'taskManagement.issueTypeCategory.standard',
      subtask: 'taskManagement.issueTypeCategory.subtask',
    },
    links: {
      parent: 'taskManagement.links.parent',
      parentPlaceholder: 'taskManagement.links.parentPlaceholder',
      children: 'taskManagement.links.children',
      type: 'taskManagement.links.type',
      targetPlaceholder: 'taskManagement.links.targetPlaceholder',
      setParentSubmit: 'taskManagement.links.setParentSubmit',
      detachParent: 'taskManagement.links.detachParent',
      addSubmit: 'taskManagement.links.addSubmit',
      remove: 'taskManagement.links.remove',
      none: 'taskManagement.links.none',
    },
    fieldPanel: {
      state: 'taskManagement.fieldPanel.state',
      noTransitions: 'taskManagement.fieldPanel.noTransitions',
      type: 'taskManagement.fieldPanel.type',
    },
    activityStream: {
      title: 'taskManagement.activityStream.title',
      empty: 'taskManagement.activityStream.empty',
      commentRemoved: 'taskManagement.activityStream.commentRemoved',
      edited: 'taskManagement.activityStream.edited',
      reply: 'taskManagement.activityStream.reply',
      edit: 'taskManagement.activityStream.edit',
      remove: 'taskManagement.activityStream.remove',
      filters: {
        all: 'taskManagement.activityStream.filters.all',
        comments: 'taskManagement.activityStream.filters.comments',
        history: 'taskManagement.activityStream.filters.history',
        time: 'taskManagement.activityStream.filters.time',
      },
    },
  } as const;
