/**
 * Typesafe translation keys for the taskManagement scope.
 * Generated automatically from pl-PL.json.
 * Do not edit this file manually.
 */
export const TASKMANAGEMENT_KEYS = {
    workflow: {
      states: {
        todo: 'taskManagement.workflow.states.todo',
        inProgress: 'taskManagement.workflow.states.inProgress',
        done: 'taskManagement.workflow.states.done',
      },
      transitions: {
        start: 'taskManagement.workflow.transitions.start',
        return: 'taskManagement.workflow.transitions.return',
        finish: 'taskManagement.workflow.transitions.finish',
        reopen: 'taskManagement.workflow.transitions.reopen',
        close: 'taskManagement.workflow.transitions.close',
        reopenToTodo: 'taskManagement.workflow.transitions.reopenToTodo',
      },
      categories: {
        todo: 'taskManagement.workflow.categories.todo',
        inProgress: 'taskManagement.workflow.categories.inProgress',
        done: 'taskManagement.workflow.categories.done',
      },
    },
    priority: {
      lowest: 'taskManagement.priority.lowest',
      low: 'taskManagement.priority.low',
      normal: 'taskManagement.priority.normal',
      high: 'taskManagement.priority.high',
      critical: 'taskManagement.priority.critical',
    },
    projectKind: {
      delivery: 'taskManagement.projectKind.delivery',
      intake: 'taskManagement.projectKind.intake',
    },
    projectMemberRole: {
      viewer: 'taskManagement.projectMemberRole.viewer',
      contributor: 'taskManagement.projectMemberRole.contributor',
      lead: 'taskManagement.projectMemberRole.lead',
    },
  } as const;
