/**
 * Typesafe translation keys for the project scope.
 * Generated automatically from pl-PL.json.
 * Do not edit this file manually.
 */
export const PROJECT_KEYS = {
    title: 'project.title',
    filters: {
      text: {
        label: 'project.filters.text.label',
        placeholder: 'project.filters.text.placeholder',
      },
      kind: {
        label: 'project.filters.kind.label',
        placeholder: 'project.filters.kind.placeholder',
        delivery: 'project.filters.kind.delivery',
        intake: 'project.filters.kind.intake',
      },
      onlyMine: {
        label: 'project.filters.onlyMine.label',
      },
    },
    table: {
      emptyMessage: 'project.table.emptyMessage',
      columns: {
        code: 'project.table.columns.code',
        name: 'project.table.columns.name',
        kind: 'project.table.columns.kind',
        openIssues: 'project.table.columns.openIssues',
        members: 'project.table.columns.members',
        fieldScheme: 'project.table.columns.fieldScheme',
      },
      noScheme: 'project.table.noScheme',
    },
    detail: {
      loading: 'project.detail.loading',
      notFound: 'project.detail.notFound',
      back: 'project.detail.back',
      fields: {
        title: 'project.detail.fields.title',
        scheme: {
          label: 'project.detail.fields.scheme.label',
          placeholder: 'project.detail.fields.scheme.placeholder',
          detach: 'project.detail.fields.scheme.detach',
          detachHint: 'project.detail.fields.scheme.detachHint',
          empty: 'project.detail.fields.scheme.empty',
        },
        columns: {
          code: 'project.detail.fields.columns.code',
          name: 'project.detail.fields.columns.name',
          type: 'project.detail.fields.columns.type',
          slot: 'project.detail.fields.columns.slot',
          required: 'project.detail.fields.columns.required',
        },
        noSlot: 'project.detail.fields.noSlot',
        slotWarning: 'project.detail.fields.slotWarning',
        add: {
          title: 'project.detail.fields.add.title',
          code: 'project.detail.fields.add.code',
          codeHint: 'project.detail.fields.add.codeHint',
          nameKey: 'project.detail.fields.add.nameKey',
          type: 'project.detail.fields.add.type',
          slot: 'project.detail.fields.add.slot',
          slotNone: 'project.detail.fields.add.slotNone',
          options: 'project.detail.fields.add.options',
          optionsHint: 'project.detail.fields.add.optionsHint',
          required: 'project.detail.fields.add.required',
          submit: 'project.detail.fields.add.submit',
          name: 'project.detail.fields.add.name',
          nameKeyHint: 'project.detail.fields.add.nameKeyHint',
          slotsExhausted: 'project.detail.fields.add.slotsExhausted',
        },
        remove: {
          label: 'project.detail.fields.remove.label',
          confirmTitle: 'project.detail.fields.remove.confirmTitle',
          confirmMessage: 'project.detail.fields.remove.confirmMessage',
        },
        types: {
          text: 'project.detail.fields.types.text',
          number: 'project.detail.fields.types.number',
          date: 'project.detail.fields.types.date',
          user: 'project.detail.fields.types.user',
          select: 'project.detail.fields.types.select',
        },
      },
      types: {
        title: 'project.detail.types.title',
        empty: 'project.detail.types.empty',
        scheme: {
          label: 'project.detail.types.scheme.label',
          placeholder: 'project.detail.types.scheme.placeholder',
          attach: 'project.detail.types.scheme.attach',
        },
        columns: {
          name: 'project.detail.types.columns.name',
          category: 'project.detail.types.columns.category',
          icon: 'project.detail.types.columns.icon',
        },
        add: {
          title: 'project.detail.types.add.title',
          name: 'project.detail.types.add.name',
          icon: 'project.detail.types.add.icon',
          iconHint: 'project.detail.types.add.iconHint',
          category: 'project.detail.types.add.category',
          submit: 'project.detail.types.add.submit',
        },
        remove: {
          label: 'project.detail.types.remove.label',
          confirmTitle: 'project.detail.types.remove.confirmTitle',
          confirmMessage: 'project.detail.types.remove.confirmMessage',
        },
      },
      sla: {
        title: 'project.detail.sla.title',
        empty: 'project.detail.sla.empty',
        responseMinutes: 'project.detail.sla.responseMinutes',
        resolutionMinutes: 'project.detail.sla.resolutionMinutes',
        workStartTime: 'project.detail.sla.workStartTime',
        workEndTime: 'project.detail.sla.workEndTime',
        timeHint: 'project.detail.sla.timeHint',
        workingDays: 'project.detail.sla.workingDays',
        days: {
          monday: 'project.detail.sla.days.monday',
          tuesday: 'project.detail.sla.days.tuesday',
          wednesday: 'project.detail.sla.days.wednesday',
          thursday: 'project.detail.sla.days.thursday',
          friday: 'project.detail.sla.days.friday',
          saturday: 'project.detail.sla.days.saturday',
          sunday: 'project.detail.sla.days.sunday',
        },
        save: 'project.detail.sla.save',
        saveFailed: 'project.detail.sla.saveFailed',
      },
    },
  } as const;
