//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.0.0 (NJsonSchema v11.6.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

export interface ICatalogClient {
    /**
     * @return OK
     */
    getWarranty(body: GetWarrantyRequest): Observable<WarrantyDto[]>;
    /**
     * @return OK
     */
    searchWarranty(body: SearchWarrantyRequest): Observable<SearchResponse>;
    /**
     * @return OK
     */
    getProduct(body: GetProductRequest): Observable<ProductDto[]>;
    /**
     * @return OK
     */
    searchProduct(body: SearchProductRequest): Observable<SearchResponse>;
    /**
     * Seryjne zakładanie produktów z obsługą błędów cząstkowych
     * @return OK
     */
    productCreateMultipleCommand(body: BatchCommandOfProductCreateCommandAndSearchProductRequest): Observable<BatchResult>;
    /**
     * Seryjna zmiana modelu i kategorii produktów z obsługą błędów cząstkowych
     * @return OK
     */
    productSetClassificationMultipleCommand(body: BatchCommandOfProductSetClassificationCommandAndSearchProductRequest): Observable<BatchResult>;
    /**
     * Seryjna aktualizacja nazw produktów z obsługą błędów cząstkowych
     * @return OK
     */
    productSetNameMultipleCommand(body: BatchCommandOfProductSetNameCommandAndSearchProductRequest): Observable<BatchResult>;
    /**
     * Seryjna aktualizacja cen produktów z obsługą błędów cząstkowych
     * @return OK
     */
    productSetPriceMultipleCommand(body: BatchCommandOfProductSetPriceCommandAndSearchProductRequest): Observable<BatchResult>;
    /**
     * @return OK
     */
    getMultimedia(body: GetMultimediaRequest): Observable<MultimediaDto[]>;
    /**
     * @return OK
     */
    searchMultimedia(body: SearchMultimediaRequest): Observable<SearchResponse>;
    /**
     * @return OK
     */
    getModel(body: GetModelRequest): Observable<ModelDto[]>;
    /**
     * @return OK
     */
    searchModel(body: SearchModelRequest): Observable<SearchResponse>;
    /**
     * @return OK
     */
    jobCancel(body: JobControlRequest): Observable<JobCancelResult>;
    /**
     * @return OK
     */
    jobRetryFailed(body: JobControlRequest): Observable<JobRetryFailedResult>;
    /**
     * @return OK
     */
    getCodeType(body: GetCodeTypeRequest): Observable<CodeTypeDto[]>;
    /**
     * @return OK
     */
    searchCodeType(body: SearchCodeTypeRequest): Observable<SearchResponse>;
    /**
     * @return OK
     */
    getCategory(body: GetCategoryRequest): Observable<CategoryDto[]>;
    /**
     * @return OK
     */
    getCategoryChildren(body: GetCategoryChildrenRequest): Observable<GetCategoryChildrenResponse>;
    /**
     * @return OK
     */
    searchCategory(body: SearchCategoryRequest): Observable<SearchResponse>;
    /**
     * @return OK
     */
    searchCategoryTree(body: SearchCategoryTreeRequest): Observable<SearchCategoryTreeResponse>;
    /**
     * @return OK
     */
    getAttribute(body: GetAttributeRequest): Observable<AttributeDefinitionDto[]>;
    /**
     * @return OK
     */
    searchAttribute(body: SearchAttributeRequest): Observable<SearchResponse>;
}

@Injectable({
    providedIn: 'root'
})
export class CatalogClient implements ICatalogClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "http://localhost:5149/";
    }

    /**
     * @return OK
     */
    getWarranty(body: GetWarrantyRequest): Observable<WarrantyDto[]> {
        let url_ = this.baseUrl + "/warranty/getWarranty";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetWarranty(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetWarranty(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<WarrantyDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<WarrantyDto[]>;
        }));
    }

    protected processGetWarranty(response: HttpResponseBase): Observable<WarrantyDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as WarrantyDto[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    searchWarranty(body: SearchWarrantyRequest): Observable<SearchResponse> {
        let url_ = this.baseUrl + "/warranty/searchWarranty";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearchWarranty(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearchWarranty(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SearchResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SearchResponse>;
        }));
    }

    protected processSearchWarranty(response: HttpResponseBase): Observable<SearchResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SearchResponse;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getProduct(body: GetProductRequest): Observable<ProductDto[]> {
        let url_ = this.baseUrl + "/product/getProduct";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetProduct(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetProduct(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ProductDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ProductDto[]>;
        }));
    }

    protected processGetProduct(response: HttpResponseBase): Observable<ProductDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ProductDto[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    searchProduct(body: SearchProductRequest): Observable<SearchResponse> {
        let url_ = this.baseUrl + "/product/searchProduct";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearchProduct(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearchProduct(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SearchResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SearchResponse>;
        }));
    }

    protected processSearchProduct(response: HttpResponseBase): Observable<SearchResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SearchResponse;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjne zakładanie produktów z obsługą błędów cząstkowych
     * @return OK
     */
    productCreateMultipleCommand(body: BatchCommandOfProductCreateCommandAndSearchProductRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/product/product/batch-create";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processProductCreateMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processProductCreateMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processProductCreateMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjna zmiana modelu i kategorii produktów z obsługą błędów cząstkowych
     * @return OK
     */
    productSetClassificationMultipleCommand(body: BatchCommandOfProductSetClassificationCommandAndSearchProductRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/product/product/batch-set-classification";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processProductSetClassificationMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processProductSetClassificationMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processProductSetClassificationMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjna aktualizacja nazw produktów z obsługą błędów cząstkowych
     * @return OK
     */
    productSetNameMultipleCommand(body: BatchCommandOfProductSetNameCommandAndSearchProductRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/product/product/batch-set-name";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processProductSetNameMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processProductSetNameMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processProductSetNameMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjna aktualizacja cen produktów z obsługą błędów cząstkowych
     * @return OK
     */
    productSetPriceMultipleCommand(body: BatchCommandOfProductSetPriceCommandAndSearchProductRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/product/product/batch-set-price";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processProductSetPriceMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processProductSetPriceMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processProductSetPriceMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getMultimedia(body: GetMultimediaRequest): Observable<MultimediaDto[]> {
        let url_ = this.baseUrl + "/multimedia/getMultimedia";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetMultimedia(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetMultimedia(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<MultimediaDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<MultimediaDto[]>;
        }));
    }

    protected processGetMultimedia(response: HttpResponseBase): Observable<MultimediaDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MultimediaDto[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    searchMultimedia(body: SearchMultimediaRequest): Observable<SearchResponse> {
        let url_ = this.baseUrl + "/multimedia/searchMultimedia";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearchMultimedia(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearchMultimedia(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SearchResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SearchResponse>;
        }));
    }

    protected processSearchMultimedia(response: HttpResponseBase): Observable<SearchResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SearchResponse;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getModel(body: GetModelRequest): Observable<ModelDto[]> {
        let url_ = this.baseUrl + "/model/getModel";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetModel(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetModel(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ModelDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ModelDto[]>;
        }));
    }

    protected processGetModel(response: HttpResponseBase): Observable<ModelDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ModelDto[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    searchModel(body: SearchModelRequest): Observable<SearchResponse> {
        let url_ = this.baseUrl + "/model/searchModel";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearchModel(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearchModel(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SearchResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SearchResponse>;
        }));
    }

    protected processSearchModel(response: HttpResponseBase): Observable<SearchResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SearchResponse;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    jobCancel(body: JobControlRequest): Observable<JobCancelResult> {
        let url_ = this.baseUrl + "/job/cancel";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processJobCancel(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processJobCancel(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<JobCancelResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<JobCancelResult>;
        }));
    }

    protected processJobCancel(response: HttpResponseBase): Observable<JobCancelResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as JobCancelResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    jobRetryFailed(body: JobControlRequest): Observable<JobRetryFailedResult> {
        let url_ = this.baseUrl + "/job/retry-failed";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processJobRetryFailed(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processJobRetryFailed(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<JobRetryFailedResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<JobRetryFailedResult>;
        }));
    }

    protected processJobRetryFailed(response: HttpResponseBase): Observable<JobRetryFailedResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as JobRetryFailedResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getCodeType(body: GetCodeTypeRequest): Observable<CodeTypeDto[]> {
        let url_ = this.baseUrl + "/codeType/getCodeType";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetCodeType(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCodeType(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CodeTypeDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CodeTypeDto[]>;
        }));
    }

    protected processGetCodeType(response: HttpResponseBase): Observable<CodeTypeDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as CodeTypeDto[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    searchCodeType(body: SearchCodeTypeRequest): Observable<SearchResponse> {
        let url_ = this.baseUrl + "/codeType/searchCodeType";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearchCodeType(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearchCodeType(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SearchResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SearchResponse>;
        }));
    }

    protected processSearchCodeType(response: HttpResponseBase): Observable<SearchResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SearchResponse;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getCategory(body: GetCategoryRequest): Observable<CategoryDto[]> {
        let url_ = this.baseUrl + "/category/getCategory";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetCategory(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCategory(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CategoryDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CategoryDto[]>;
        }));
    }

    protected processGetCategory(response: HttpResponseBase): Observable<CategoryDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as CategoryDto[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getCategoryChildren(body: GetCategoryChildrenRequest): Observable<GetCategoryChildrenResponse> {
        let url_ = this.baseUrl + "/category/getCategoryChildren";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetCategoryChildren(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCategoryChildren(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetCategoryChildrenResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetCategoryChildrenResponse>;
        }));
    }

    protected processGetCategoryChildren(response: HttpResponseBase): Observable<GetCategoryChildrenResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as GetCategoryChildrenResponse;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    searchCategory(body: SearchCategoryRequest): Observable<SearchResponse> {
        let url_ = this.baseUrl + "/category/searchCategory";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearchCategory(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearchCategory(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SearchResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SearchResponse>;
        }));
    }

    protected processSearchCategory(response: HttpResponseBase): Observable<SearchResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SearchResponse;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    searchCategoryTree(body: SearchCategoryTreeRequest): Observable<SearchCategoryTreeResponse> {
        let url_ = this.baseUrl + "/category/searchCategoryTree";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearchCategoryTree(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearchCategoryTree(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SearchCategoryTreeResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SearchCategoryTreeResponse>;
        }));
    }

    protected processSearchCategoryTree(response: HttpResponseBase): Observable<SearchCategoryTreeResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SearchCategoryTreeResponse;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getAttribute(body: GetAttributeRequest): Observable<AttributeDefinitionDto[]> {
        let url_ = this.baseUrl + "/attribute/getAttribute";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetAttribute(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetAttribute(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<AttributeDefinitionDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<AttributeDefinitionDto[]>;
        }));
    }

    protected processGetAttribute(response: HttpResponseBase): Observable<AttributeDefinitionDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AttributeDefinitionDto[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    searchAttribute(body: SearchAttributeRequest): Observable<SearchResponse> {
        let url_ = this.baseUrl + "/attribute/searchAttribute";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearchAttribute(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearchAttribute(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SearchResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SearchResponse>;
        }));
    }

    protected processSearchAttribute(response: HttpResponseBase): Observable<SearchResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SearchResponse;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export interface AttributeDefinitionDto {
    uuid: string;
    code: string;
    name: string;
    kind: string;
    dataType: string;
    isMultiValue: boolean;
    sortOrder: number;
    options: AttributeOptionDto[];

    [key: string]: any;
}

export interface AttributeOptionDto {
    uuid: string;
    code: string;
    name: string;
    sortOrder: number;

    [key: string]: any;
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfProductCreateCommandAndSearchProductRequest {
    commands?: ProductCreateCommand[] | undefined;
    templateCommand?: ProductCreateCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchProductRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfProductSetClassificationCommandAndSearchProductRequest {
    commands?: ProductSetClassificationCommand[] | undefined;
    templateCommand?: ProductSetClassificationCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchProductRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfProductSetNameCommandAndSearchProductRequest {
    commands?: ProductSetNameCommand[] | undefined;
    templateCommand?: ProductSetNameCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchProductRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfProductSetPriceCommandAndSearchProductRequest {
    commands?: ProductSetPriceCommand[] | undefined;
    templateCommand?: ProductSetPriceCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchProductRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

export interface BatchResult {
    jobUuid?: string;

    [key: string]: any;
}

export interface CategoryDto {
    uuid: string;
    name: string;
    parentUuid: string | undefined;

    [key: string]: any;
}

export interface CategoryTreeNodeDto {
    uuid: string;
    name: string;
    parentUuid: string | undefined;
    hasChildren: boolean;
    childCount: number;
    descendantCount: number;

    [key: string]: any;
}

export interface CodeTypeDto {
    uuid: string;
    symbol: string;
    name: string;
    pattern: string | undefined;
    isUnique: boolean;
    sortOrder: number;

    [key: string]: any;
}

export interface GetAttributeRequest {
    uuids?: string[] | undefined;

    [key: string]: any;
}

export interface GetCategoryChildrenRequest {
    parentUuid?: string | undefined;
    pageIndex?: number;
    pageSize?: number;

    [key: string]: any;
}

export interface GetCategoryChildrenResponse {
    nodes?: CategoryTreeNodeDto[];
    totalCount?: number;

    [key: string]: any;
}

export interface GetCategoryRequest {
    uuids?: string[] | undefined;

    [key: string]: any;
}

export interface GetCodeTypeRequest {
    uuids?: string[] | undefined;

    [key: string]: any;
}

export interface GetModelRequest {
    uuids?: string[] | undefined;

    [key: string]: any;
}

export interface GetMultimediaRequest {
    uuids?: string[] | undefined;

    [key: string]: any;
}

export interface GetProductRequest {
    uuids?: string[] | undefined;

    [key: string]: any;
}

export interface GetWarrantyRequest {
    uuids?: string[] | undefined;

    [key: string]: any;
}

/** Wynik anulowania — status zwrócony od razu, bez czekania na runner. */
export interface JobCancelResult {
    jobUuid?: string;
    status?: string;

    [key: string]: any;
}

/** Żądanie sterujące zadaniem masowym po jego identyfikatorze. */
export interface JobControlRequest {
    jobUuid?: string;

    [key: string]: any;
}

/** Wynik ponowienia — identyfikator nowo utworzonego zadania. */
export interface JobRetryFailedResult {
    newJobUuid?: string;

    [key: string]: any;
}

export interface ModelDto {
    uuid: string;
    name: string;

    [key: string]: any;
}

export interface MultimediaDto {
    uuid: string;
    fileName: string;
    mediaType: string;
    thumbnailUrl: string | undefined;
    originalUrl: string;
    fileSize: number;
    mimeType: string;
    sortOrder: number;
    createdAt: Date;

    [key: string]: any;
}

export interface ProductAttributeValueDto {
    uuid: string;
    attributeUuid: string;
    kind: string;
    optionUuid: string | undefined;
    multimediaUuid: string | undefined;
    valueText: string | undefined;
    valueNumber: number | undefined;
    valueBoolean: boolean | undefined;
    valueDate: Date | undefined;
    sortOrder: number;

    [key: string]: any;
}

export interface ProductCodeDto {
    uuid: string;
    codeTypeUuid: string;
    value: string;

    [key: string]: any;
}

export interface ProductCreateCommand {
    uuid?: string;
    name?: string;
    price?: number;

    [key: string]: any;
}

export interface ProductDto {
    uuid: string;
    name: string;
    categoryUuids: string[];
    multimediaUuids: string[];
    warranties: ProductWarrantyDto[];
    codes: ProductCodeDto[];
    attributes: ProductAttributeValueDto[];
    modelUuid: string | undefined;
    price: number;
    availableFrom: Date | undefined;
    status: string;
    available: boolean;
    image: string | undefined;

    [key: string]: any;
}

export interface ProductSetClassificationCommand {
    uuid?: string;
    modelUuid?: string | undefined;
    categoryUuids?: string[];

    [key: string]: any;
}

export interface ProductSetNameCommand {
    uuid?: string;
    name?: string;

    [key: string]: any;
}

export interface ProductSetPriceCommand {
    uuid?: string;
    price?: number;

    [key: string]: any;
}

export interface ProductWarrantyDto {
    warrantyUuid: string;
    durationMonths: number;

    [key: string]: any;
}

export interface SearchAttributeRequest {
    attributeId?: string | undefined;
    name?: string | undefined;
    kind?: string | undefined;
    page?: number;
    pageSize?: number;
    sorts?: SortOption[] | undefined;

    [key: string]: any;
}

export interface SearchCategoryRequest {
    name?: string | undefined;
    page?: number;
    pageSize?: number;
    sorts?: SortOption[] | undefined;

    [key: string]: any;
}

export interface SearchCategoryTreeRequest {
    search?: string | undefined;

    [key: string]: any;
}

export interface SearchCategoryTreeResponse {
    matches?: CategoryTreeNodeDto[];
    ancestors?: CategoryTreeNodeDto[];
    totalCount?: number;

    [key: string]: any;
}

export interface SearchCodeTypeRequest {
    codeTypeId?: string | undefined;
    name?: string | undefined;
    page?: number;
    pageSize?: number;
    sorts?: SortOption[] | undefined;

    [key: string]: any;
}

export interface SearchModelRequest {
    name?: string | undefined;
    page?: number;
    pageSize?: number;
    sorts?: SortOption[] | undefined;

    [key: string]: any;
}

export interface SearchMultimediaRequest {
    uuids?: string[] | undefined;
    page?: number;
    pageSize?: number;
    sorts?: SortOption[] | undefined;

    [key: string]: any;
}

export interface SearchProductRequest {
    productId?: string | undefined;
    modelId?: string | undefined;
    productType?: string | undefined;
    manufacturer?: string | undefined;
    model?: string | undefined;
    category?: TreeSelectionRequest | undefined;
    attribute?: string | undefined;
    attributeId?: string | undefined;
    attributeOptionId?: string | undefined;
    productCode?: string | undefined;
    codeTypeId?: string | undefined;
    territoryCode?: string | undefined;
    summaryReport?: boolean | undefined;
    page?: number;
    pageSize?: number;
    sorts?: SortOption[] | undefined;

    [key: string]: any;
}

export interface SearchResponse {
    uuids?: string[];
    totalCount?: number;

    [key: string]: any;
}

export interface SearchWarrantyRequest {
    warrantyId?: string | undefined;
    name?: string | undefined;
    page?: number;
    pageSize?: number;
    sorts?: SortOption[] | undefined;

    [key: string]: any;
}

export interface SortOption {
    field?: string;
    order?: number;

    [key: string]: any;
}

/** Deskryptor dowolnego zaznaczenia w drzewie — odpowiednik `ErpTreeSelectionValue` z frontendu (`erp-tree-selection.model.ts`). Zamiast płaskiej listy uuid (nieskalowalnej — zaznaczenie korzenia z tysiącami potomków nie może wymagać wypisania ich wszystkich w request body), request niesie deskryptor: pojedyncze znaczniki (List&lt;Guid&gt; TreeSelectionRequest.Ids) obok poddrzew z wyjątkami (List&lt;Guid&gt; TreeSelectionRequest.SubtreeRoots/List&lt;Guid&gt; TreeSelectionRequest.Excluded). Rozstrzygnięcie przynależności konkretnego węzła do zaznaczenia wymaga znajomości hierarchii (mapy dziecko→rodzic) — patrz TreeSelectionResolver. Wzorcowy request-side model do wielokrotnego użycia przy innych filtrach drzewiastych (kategorie, struktura magazynów, drzewo zadań itp.) — nie tworzyć ad-hoc odpowiedników per moduł. */
export interface TreeSelectionRequest {
    /** Niezależnie zaznaczone węzły — zawsze włączone, bez względu na SubtreeRoots/Excluded. */
    ids?: string[];
    /** Korzenie zaznaczonych poddrzew (kaskadowo obejmują potomków). */
    subtreeRoots?: string[];
    /** Wykluczenia (carve-outs) wewnątrz zaznaczonych poddrzew — w tym wzorzec
            „poddrzewo X bez samego X”: `SubtreeRoots: [X], Excluded: [X]`. */
    excluded?: string[];

    [key: string]: any;
}

export interface WarrantyDto {
    uuid: string;
    name: string;
    durationMonths: number;
    description: string;

    [key: string]: any;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}