/* This file is generated by pnpm docs:generate. Do not edit. */
export const CATALOG_DOCUMENTATION_ARTICLE_IDS = {
  overview: 'catalog.overview',
  products: {
    listAndFilters: 'catalog.products.list-and-filters',
    bulkEdit: 'catalog.products.bulk-edit',
  },
  multimedia: {
    library: 'catalog.multimedia.library',
  },
  backgroundJobs: 'catalog.background-jobs',
  permissions: 'catalog.permissions',
  troubleshooting: 'catalog.troubleshooting',
} as const;
