/**
 * Typesafe translation keys for the grantAudit scope.
 * Generated automatically from pl-PL.json.
 * Do not edit this file manually.
 */
export const GRANTAUDIT_KEYS = {
    title: 'grantAudit.title',
    subtitle: 'grantAudit.subtitle',
    menuLabel: 'grantAudit.menuLabel',
    table: {
      emptyMessage: 'grantAudit.table.emptyMessage',
      columns: {
        occurredAt: 'grantAudit.table.columns.occurredAt',
        actor: 'grantAudit.table.columns.actor',
        subject: 'grantAudit.table.columns.subject',
        action: 'grantAudit.table.columns.action',
        target: 'grantAudit.table.columns.target',
        source: 'grantAudit.table.columns.source',
      },
    },
    filters: {
      subjectUuid: {
        label: 'grantAudit.filters.subjectUuid.label',
        placeholder: 'grantAudit.filters.subjectUuid.placeholder',
      },
      subjectType: {
        label: 'grantAudit.filters.subjectType.label',
        placeholder: 'grantAudit.filters.subjectType.placeholder',
      },
      action: {
        label: 'grantAudit.filters.action.label',
        placeholder: 'grantAudit.filters.action.placeholder',
      },
    },
  } as const;
