/**
 * Typesafe translation keys for the job scope.
 * Generated automatically from pl-PL.json.
 * Do not edit this file manually.
 */
export const JOB_KEYS = {
    title: 'job.title',
    empty: 'job.empty',
    showAll: 'job.showAll',
    clearFinished: 'job.clearFinished',
    unknownCommand: 'job.unknownCommand',
    progress: 'job.progress',
    errorsSummary: 'job.errorsSummary',
    status: {
      pending: 'job.status.pending',
      running: 'job.status.running',
      completed: 'job.status.completed',
      completedWithErrors: 'job.status.completedWithErrors',
      failed: 'job.status.failed',
      cancelled: 'job.status.cancelled',
      finishing: 'job.status.finishing',
    },
    history: {
      title: 'job.history.title',
      empty: 'job.history.empty',
      refresh: 'job.history.refresh',
      filter: {
        all: 'job.history.filter.all',
        active: 'job.history.filter.active',
        finished: 'job.history.filter.finished',
      },
      summary: 'job.history.summary',
    },
    page: {
      filters: {
        title: 'job.page.filters.title',
        trackingId: 'job.page.filters.trackingId',
        queueId: 'job.page.filters.queueId',
        clientId: 'job.page.filters.clientId',
      },
      toolbar: {
        group: 'job.page.toolbar.group',
        refresh: 'job.page.toolbar.refresh',
        clearFinished: 'job.page.toolbar.clearFinished',
      },
      table: {
        groups: {
          job: 'job.page.table.groups.job',
          progress: 'job.page.table.groups.progress',
        },
        columns: {
          command: 'job.page.table.columns.command',
          status: 'job.page.table.columns.status',
          progress: 'job.page.table.columns.progress',
          succeeded: 'job.page.table.columns.succeeded',
          failed: 'job.page.table.columns.failed',
          createdAt: 'job.page.table.columns.createdAt',
          errors: 'job.page.table.columns.errors',
          result: 'job.page.table.columns.result',
        },
        emptyCell: 'job.page.table.emptyCell',
      },
    },
    download: 'job.download',
    downloadFailed: 'job.downloadFailed',
  } as const;
