/**
 * Typesafe translation keys for the roles scope.
 * Generated automatically from pl-PL.json.
 * Do not edit this file manually.
 */
export const ROLES_KEYS = {
  title: 'roles.title',
  subtitle: 'roles.subtitle',
  table: {
    emptyMessage: 'roles.table.emptyMessage',
    columns: {
      code: 'roles.table.columns.code',
      name: 'roles.table.columns.name',
      isSystem: 'roles.table.columns.isSystem',
      permissionCount: 'roles.table.columns.permissionCount',
      memberCount: 'roles.table.columns.memberCount',
    },
  },
  detail: {
    emptySelection: 'roles.detail.emptySelection',
    systemBadge: 'roles.detail.systemBadge',
    tabs: {
      permissions: 'roles.detail.tabs.permissions',
      members: 'roles.detail.tabs.members',
      containers: 'roles.detail.tabs.containers',
      holders: 'roles.detail.tabs.holders',
    },
    permissions: {
      emptyMessage: 'roles.detail.permissions.emptyMessage',
      removeConfirmTitle: 'roles.detail.permissions.removeConfirmTitle',
      removeConfirmMessage: 'roles.detail.permissions.removeConfirmMessage',
      removeConfirmYes: 'roles.detail.permissions.removeConfirmYes',
      removeConfirmNo: 'roles.detail.permissions.removeConfirmNo',
    },
    members: {
      emptyMessage: 'roles.detail.members.emptyMessage',
      columns: {
        code: 'roles.detail.members.columns.code',
        name: 'roles.detail.members.columns.name',
      },
      removeConfirmTitle: 'roles.detail.members.removeConfirmTitle',
      removeConfirmMessage: 'roles.detail.members.removeConfirmMessage',
      removeConfirmYes: 'roles.detail.members.removeConfirmYes',
      removeConfirmNo: 'roles.detail.members.removeConfirmNo',
    },
    containers: {
      emptyMessage: 'roles.detail.containers.emptyMessage',
      columns: {
        code: 'roles.detail.containers.columns.code',
        name: 'roles.detail.containers.columns.name',
      },
    },
    holders: {
      emptyMessage: 'roles.detail.holders.emptyMessage',
      columns: {
        email: 'roles.detail.holders.columns.email',
        displayName: 'roles.detail.holders.columns.displayName',
      },
    },
  },
  commands: {
    create: {
      label: 'roles.commands.create.label',
      modalTitle: 'roles.commands.create.modalTitle',
      codeLabel: 'roles.commands.create.codeLabel',
      codePlaceholder: 'roles.commands.create.codePlaceholder',
      nameLabel: 'roles.commands.create.nameLabel',
      namePlaceholder: 'roles.commands.create.namePlaceholder',
      descriptionLabel: 'roles.commands.create.descriptionLabel',
      descriptionPlaceholder: 'roles.commands.create.descriptionPlaceholder',
      submitButton: 'roles.commands.create.submitButton',
    },
    addPermission: {
      label: 'roles.commands.addPermission.label',
      modalTitle: 'roles.commands.addPermission.modalTitle',
      permissionLabel: 'roles.commands.addPermission.permissionLabel',
      submitButton: 'roles.commands.addPermission.submitButton',
    },
    addMember: {
      label: 'roles.commands.addMember.label',
      modalTitle: 'roles.commands.addMember.modalTitle',
      roleLabel: 'roles.commands.addMember.roleLabel',
      submitButton: 'roles.commands.addMember.submitButton',
    },
  },
} as const;
