/**
 * Typesafe translation keys for the board scope.
 * Generated automatically from pl-PL.json.
 * Do not edit this file manually.
 */
export const BOARD_KEYS = {
    title: 'board.title',
    loading: 'board.loading',
    notFound: 'board.notFound',
    empty: {
      columns: 'board.empty.columns',
      column: 'board.empty.column',
    },
    column: {
      count: 'board.column.count',
    },
    card: {
      unassigned: 'board.card.unassigned',
    },
    move: {
      failed: 'board.move.failed',
      blocked: 'board.move.blocked',
    },
    warnings: {
      openChildren: {
        title: 'board.warnings.openChildren.title',
        message: 'board.warnings.openChildren.message',
        confirm: 'board.warnings.openChildren.confirm',
      },
      blocked: {
        title: 'board.warnings.blocked.title',
        message: 'board.warnings.blocked.message',
        confirm: 'board.warnings.blocked.confirm',
      },
    },
  } as const;
