// <auto-generated />
using System;
using Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260815104834_ProductLinkGeneratedKeys")]
    partial class ProductLinkGeneratedKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_category");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_category_name");

                    b.HasIndex("ParentUuid", "Name")
                        .HasDatabaseName("ix_category_parent_uuid_name");

                    b.ToTable("category", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Categories.CategoryClosureEntry", b =>
                {
                    b.Property<Guid>("AncestorUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("ancestor_uuid");

                    b.Property<Guid>("DescendantUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("descendant_uuid");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.HasKey("AncestorUuid", "DescendantUuid")
                        .HasName("pk_category_closure");

                    b.HasIndex("AncestorUuid", "Depth")
                        .HasDatabaseName("ix_category_closure_ancestor_uuid_depth");

                    b.HasIndex("DescendantUuid", "Depth")
                        .HasDatabaseName("ix_category_closure_descendant_uuid_depth");

                    b.ToTable("category_closure", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Models.ProductModel", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_model");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_model_name");

                    b.ToTable("model", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Multimedia.MultimediaAsset", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("media_type");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("original_url");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("thumbnail_url");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_multimedia");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_multimedia_created_at");

                    b.HasIndex("FileName")
                        .HasDatabaseName("ix_multimedia_file_name");

                    b.ToTable("multimedia", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("AttrColor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("attr_color");

                    b.Property<string>("AttrWeight")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("attr_weight");

                    b.Property<DateTimeOffset?>("AvailableFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_from");

                    b.Property<string>("DuplicateKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("duplicate_key");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ean");

                    b.Property<string>("Image")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image");

                    b.Property<Guid?>("ModelUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("model_uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_product");

                    b.HasIndex("AvailableFrom")
                        .HasDatabaseName("ix_product_available_from");

                    b.HasIndex("DuplicateKey")
                        .IsUnique()
                        .HasDatabaseName("ix_product_duplicate_key")
                        .HasFilter("duplicate_key IS NOT NULL");

                    b.HasIndex("Ean")
                        .HasDatabaseName("ix_product_ean");

                    b.HasIndex("ModelUuid")
                        .HasDatabaseName("ix_product_model_uuid");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_product_name");

                    b.HasIndex("Price")
                        .HasDatabaseName("ix_product_price");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_product_sku");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_product_status");

                    b.ToTable("product", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.ProductCategoryLink", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CategoryUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("category_uuid");

                    b.Property<Guid>("ProductUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("product_uuid");

                    b.HasKey("Uuid")
                        .HasName("pk_product_category");

                    b.HasIndex("CategoryUuid")
                        .HasDatabaseName("ix_product_category_category_uuid");

                    b.HasIndex("ProductUuid", "CategoryUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_product_category_product_uuid_category_uuid");

                    b.ToTable("product_category", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.ProductMultimediaLink", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("MultimediaUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("multimedia_uuid");

                    b.Property<Guid>("ProductUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("product_uuid");

                    b.HasKey("Uuid")
                        .HasName("pk_product_multimedia");

                    b.HasIndex("MultimediaUuid")
                        .HasDatabaseName("ix_product_multimedia_multimedia_uuid");

                    b.HasIndex("ProductUuid", "MultimediaUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_product_multimedia_product_uuid_multimedia_uuid");

                    b.ToTable("product_multimedia", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.ProductWarranty", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("integer")
                        .HasColumnName("duration_months");

                    b.Property<Guid>("ProductUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("product_uuid");

                    b.Property<Guid>("WarrantyUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("warranty_uuid");

                    b.HasKey("Uuid")
                        .HasName("pk_product_warranty");

                    b.HasIndex("WarrantyUuid")
                        .HasDatabaseName("ix_product_warranty_warranty_uuid");

                    b.HasIndex("ProductUuid", "WarrantyUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_product_warranty_product_uuid_warranty_uuid");

                    b.ToTable("product_warranty", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Warranties.Warranty", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("description");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("integer")
                        .HasColumnName("duration_months");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_warranty");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_warranty_name");

                    b.ToTable("warranty", "catalog");
                });

            modelBuilder.Entity("Erp.BuildingBlocks.Jobs.Job", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("ClientId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_id");

                    b.Property<string>("CommandJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("command_json");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("command_type");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpireOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_on");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("QueueId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("queue_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SucceededCount")
                        .HasColumnType("integer")
                        .HasColumnName("succeeded_count");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.Property<string>("UiMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("ui_metadata");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_job");

                    b.HasIndex("QueueId")
                        .HasDatabaseName("ix_job_queue_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_job_user_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_job_status_created_at");

                    b.ToTable("job", "catalog");
                });

            modelBuilder.Entity("Erp.BuildingBlocks.Jobs.JobItem", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("AggregateUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CommandJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("command_json");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("JobUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("job_uuid");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Uuid")
                        .HasName("pk_job_item");

                    b.HasIndex("JobUuid", "ErrorCode")
                        .HasDatabaseName("ix_job_item_job_uuid_error_code");

                    b.HasIndex("JobUuid", "Status", "Ordinal")
                        .HasDatabaseName("ix_job_item_job_uuid_status_ordinal");

                    b.ToTable("job_item", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.ProductCategoryLink", b =>
                {
                    b.HasOne("Catalog.Domain.Products.Product", null)
                        .WithMany("_categories")
                        .HasForeignKey("ProductUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_category_product_product_uuid");
                });

            modelBuilder.Entity("Catalog.Domain.Products.ProductMultimediaLink", b =>
                {
                    b.HasOne("Catalog.Domain.Products.Product", null)
                        .WithMany("_multimedia")
                        .HasForeignKey("ProductUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_multimedia_product_product_uuid");
                });

            modelBuilder.Entity("Catalog.Domain.Products.ProductWarranty", b =>
                {
                    b.HasOne("Catalog.Domain.Products.Product", null)
                        .WithMany("_warranties")
                        .HasForeignKey("ProductUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_warranty_product_product_uuid");
                });

            modelBuilder.Entity("Erp.BuildingBlocks.Jobs.JobItem", b =>
                {
                    b.HasOne("Erp.BuildingBlocks.Jobs.Job", null)
                        .WithMany("Items")
                        .HasForeignKey("JobUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_item_job_job_uuid");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Product", b =>
                {
                    b.Navigation("_categories");

                    b.Navigation("_multimedia");

                    b.Navigation("_warranties");
                });

            modelBuilder.Entity("Erp.BuildingBlocks.Jobs.Job", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
