// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagement.Infrastructure.Persistence;

#nullable disable

namespace TaskManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TaskManagementDbContext))]
    [Migration("20260827133509_IssueCommentsAndActivity")]
    partial class IssueCommentsAndActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("taskmgmt")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Erp.BuildingBlocks.Jobs.Job", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("ClientId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_id");

                    b.Property<string>("CommandJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("command_json");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("command_type");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpireOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_on");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("kind");

                    b.Property<string>("QueueId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("queue_id");

                    b.Property<string>("ResultRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("result_ref");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SucceededCount")
                        .HasColumnType("integer")
                        .HasColumnName("succeeded_count");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.Property<string>("UiMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("ui_metadata");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_job");

                    b.HasIndex("QueueId")
                        .HasDatabaseName("ix_job_queue_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_job_user_id");

                    b.HasIndex("Kind", "Status", "CreatedAt")
                        .HasDatabaseName("ix_job_kind_status_created_at");

                    b.ToTable("job", "taskmgmt");
                });

            modelBuilder.Entity("Erp.BuildingBlocks.Jobs.JobItem", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("AggregateUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CommandJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("command_json");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("JobUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("job_uuid");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Uuid")
                        .HasName("pk_job_item");

                    b.HasIndex("JobUuid", "ErrorCode")
                        .HasDatabaseName("ix_job_item_job_uuid_error_code");

                    b.HasIndex("JobUuid", "Status", "Ordinal")
                        .HasDatabaseName("ix_job_item_job_uuid_status_ordinal");

                    b.ToTable("job_item", "taskmgmt");
                });

            modelBuilder.Entity("Erp.BuildingBlocks.Persistence.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("operation");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Key")
                        .HasName("pk_idempotency_key");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_key_expires_at");

                    b.ToTable("idempotency_key", "taskmgmt");
                });

            modelBuilder.Entity("TaskManagement.Domain.Issues.Issue", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid?>("AssigneeUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_restricted");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key");

                    b.Property<Guid?>("ParentUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("project_uuid");

                    b.Property<Guid>("ReporterUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_uuid");

                    b.Property<Guid>("StateUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("state_uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<List<string>>("_previousKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("previous_keys");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_issue");

                    b.HasIndex("AssigneeUuid")
                        .HasDatabaseName("ix_issue_assignee_uuid");

                    b.HasIndex("DueAt")
                        .HasDatabaseName("ix_issue_due_at");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_issue_key");

                    b.HasIndex("ParentUuid")
                        .HasDatabaseName("ix_issue_parent_uuid");

                    b.HasIndex("ReporterUuid")
                        .HasDatabaseName("ix_issue_reporter_uuid");

                    b.HasIndex("ProjectUuid", "StateUuid")
                        .HasDatabaseName("ix_issue_project_uuid_state_uuid");

                    b.ToTable("issue", "taskmgmt");
                });

            modelBuilder.Entity("TaskManagement.Domain.Issues.IssueActivity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("ActorUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("FieldCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("field_code");

                    b.Property<Guid>("IssueUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_uuid");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("NewValue")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("new_value");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OldValue")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("old_value");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_issue_activity");

                    b.HasIndex("IssueUuid", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_issue_activity_issue_uuid_occurred_at");

                    b.ToTable("issue_activity", "taskmgmt");
                });

            modelBuilder.Entity("TaskManagement.Domain.Issues.IssueAttachment", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("ArtifactUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<Guid>("IssueUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_uuid");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("UploadedByUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_issue_attachment");

                    b.HasIndex("ArtifactUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_issue_attachment_artifact_uuid");

                    b.HasIndex("IssueUuid")
                        .HasDatabaseName("ix_issue_attachment_issue_uuid");

                    b.ToTable("issue_attachment", "taskmgmt");
                });

            modelBuilder.Entity("TaskManagement.Domain.Issues.IssueComment", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("AuthorUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("author_uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<Guid>("IssueUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_uuid");

                    b.Property<string>("OriginalBody")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("original_body");

                    b.Property<Guid?>("ParentUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_uuid");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_issue_comment");

                    b.HasIndex("ParentUuid")
                        .HasDatabaseName("ix_issue_comment_parent_uuid");

                    b.HasIndex("IssueUuid", "CreatedAt")
                        .HasDatabaseName("ix_issue_comment_issue_uuid_created_at");

                    b.ToTable("issue_comment", "taskmgmt");
                });

            modelBuilder.Entity("TaskManagement.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("WorkflowSchemeUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_scheme_uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_project");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_project_code");

                    b.ToTable("project", "taskmgmt");
                });

            modelBuilder.Entity("TaskManagement.Domain.Projects.ProjectKeyCounter", b =>
                {
                    b.Property<Guid>("ProjectUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("project_uuid");

                    b.Property<int>("NextNumber")
                        .HasColumnType("integer")
                        .HasColumnName("next_number");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("prefix");

                    b.HasKey("ProjectUuid")
                        .HasName("pk_project_key_counter");

                    b.ToTable("project_key_counter", "taskmgmt");
                });

            modelBuilder.Entity("TaskManagement.Domain.Projects.ProjectMember", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("ProjectUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("project_uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.HasKey("Uuid")
                        .HasName("pk_project_member");

                    b.HasIndex("UserUuid")
                        .HasDatabaseName("ix_project_member_user_uuid");

                    b.HasIndex("ProjectUuid", "UserUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_project_member_project_uuid_user_uuid");

                    b.ToTable("project_member", "taskmgmt");
                });

            modelBuilder.Entity("TaskManagement.Domain.Workflow.WorkflowScheme", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_workflow_scheme");

                    b.ToTable("workflow_scheme", "taskmgmt");
                });

            modelBuilder.Entity("TaskManagement.Domain.Workflow.WorkflowState", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_key");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer")
                        .HasColumnName("order_no");

                    b.Property<Guid>("SchemeUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("scheme_uuid");

                    b.HasKey("Uuid")
                        .HasName("pk_workflow_state");

                    b.HasIndex("SchemeUuid", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_state_scheme_uuid_code");

                    b.ToTable("workflow_state", "taskmgmt");
                });

            modelBuilder.Entity("TaskManagement.Domain.Workflow.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("FromStateUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("from_state_uuid");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_key");

                    b.Property<string>("RequiredPermission")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("required_permission");

                    b.Property<Guid>("SchemeUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("scheme_uuid");

                    b.Property<Guid>("ToStateUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("to_state_uuid");

                    b.HasKey("Uuid")
                        .HasName("pk_workflow_transition");

                    b.HasIndex("SchemeUuid", "FromStateUuid", "ToStateUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_transition_scheme_uuid_from_state_uuid_to_state_uu");

                    b.ToTable("workflow_transition", "taskmgmt");
                });

            modelBuilder.Entity("Erp.BuildingBlocks.Jobs.JobItem", b =>
                {
                    b.HasOne("Erp.BuildingBlocks.Jobs.Job", null)
                        .WithMany("Items")
                        .HasForeignKey("JobUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_item_job_job_uuid");
                });

            modelBuilder.Entity("TaskManagement.Domain.Issues.Issue", b =>
                {
                    b.HasOne("TaskManagement.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectUuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issue_project_project_uuid");
                });

            modelBuilder.Entity("TaskManagement.Domain.Issues.IssueActivity", b =>
                {
                    b.HasOne("TaskManagement.Domain.Issues.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_activity_issue_issue_uuid");
                });

            modelBuilder.Entity("TaskManagement.Domain.Issues.IssueAttachment", b =>
                {
                    b.HasOne("TaskManagement.Domain.Issues.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attachment_issue_issue_uuid");
                });

            modelBuilder.Entity("TaskManagement.Domain.Issues.IssueComment", b =>
                {
                    b.HasOne("TaskManagement.Domain.Issues.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_comment_issue_issue_uuid");

                    b.HasOne("TaskManagement.Domain.Issues.IssueComment", null)
                        .WithMany()
                        .HasForeignKey("ParentUuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_issue_comment_issue_comment_parent_uuid");
                });

            modelBuilder.Entity("TaskManagement.Domain.Projects.ProjectKeyCounter", b =>
                {
                    b.HasOne("TaskManagement.Domain.Projects.Project", null)
                        .WithOne()
                        .HasForeignKey("TaskManagement.Domain.Projects.ProjectKeyCounter", "ProjectUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_key_counter_project_project_uuid");
                });

            modelBuilder.Entity("TaskManagement.Domain.Projects.ProjectMember", b =>
                {
                    b.HasOne("TaskManagement.Domain.Projects.Project", null)
                        .WithMany("Members")
                        .HasForeignKey("ProjectUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_member_project_project_uuid");
                });

            modelBuilder.Entity("TaskManagement.Domain.Workflow.WorkflowState", b =>
                {
                    b.HasOne("TaskManagement.Domain.Workflow.WorkflowScheme", null)
                        .WithMany("States")
                        .HasForeignKey("SchemeUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_state_workflow_scheme_scheme_uuid");
                });

            modelBuilder.Entity("TaskManagement.Domain.Workflow.WorkflowTransition", b =>
                {
                    b.HasOne("TaskManagement.Domain.Workflow.WorkflowScheme", null)
                        .WithMany("Transitions")
                        .HasForeignKey("SchemeUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transition_workflow_scheme_scheme_uuid");
                });

            modelBuilder.Entity("Erp.BuildingBlocks.Jobs.Job", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TaskManagement.Domain.Projects.Project", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("TaskManagement.Domain.Workflow.WorkflowScheme", b =>
                {
                    b.Navigation("States");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
