/**
 * Typesafe translation keys for the identity scope.
 * Generated automatically from pl-PL.json.
 * Do not edit this file manually.
 */
export const IDENTITY_KEYS = {
    dashboard: {
      title: 'identity.dashboard.title',
      placeholder: 'identity.dashboard.placeholder',
    },
  } as const;
