/**
 * Typesafe translation keys for the identity scope.
 * Generated automatically from pl-PL.json.
 * Do not edit this file manually.
 */
export const IDENTITY_KEYS = {
    dashboard: {
      title: 'identity.dashboard.title',
      placeholder: 'identity.dashboard.placeholder',
      roleManagement: {
        title: 'identity.dashboard.roleManagement.title',
        placeholder: 'identity.dashboard.roleManagement.placeholder',
      },
    },
    grantAudit: {
      title: 'identity.grantAudit.title',
      subtitle: 'identity.grantAudit.subtitle',
      menuLabel: 'identity.grantAudit.menuLabel',
      table: {
        emptyMessage: 'identity.grantAudit.table.emptyMessage',
        columns: {
          occurredAt: 'identity.grantAudit.table.columns.occurredAt',
          actor: 'identity.grantAudit.table.columns.actor',
          subject: 'identity.grantAudit.table.columns.subject',
          action: 'identity.grantAudit.table.columns.action',
          target: 'identity.grantAudit.table.columns.target',
          source: 'identity.grantAudit.table.columns.source',
        },
      },
      filters: {
        subjectUuid: {
          label: 'identity.grantAudit.filters.subjectUuid.label',
          placeholder: 'identity.grantAudit.filters.subjectUuid.placeholder',
        },
        subjectType: {
          label: 'identity.grantAudit.filters.subjectType.label',
          placeholder: 'identity.grantAudit.filters.subjectType.placeholder',
        },
        action: {
          label: 'identity.grantAudit.filters.action.label',
          placeholder: 'identity.grantAudit.filters.action.placeholder',
        },
      },
    },
    users: {
      title: 'identity.users.title',
      subtitle: 'identity.users.subtitle',
      filters: {
        email: {
          label: 'identity.users.filters.email.label',
          placeholder: 'identity.users.filters.email.placeholder',
        },
      },
      table: {
        emptyMessage: 'identity.users.table.emptyMessage',
        columns: {
          email: 'identity.users.table.columns.email',
          displayName: 'identity.users.table.columns.displayName',
          isActive: 'identity.users.table.columns.isActive',
          roleCount: 'identity.users.table.columns.roleCount',
        },
      },
      detail: {
        emptySelection: 'identity.users.detail.emptySelection',
        statusActive: 'identity.users.detail.statusActive',
        statusInactive: 'identity.users.detail.statusInactive',
        tabs: {
          roles: 'identity.users.detail.tabs.roles',
          permissions: 'identity.users.detail.tabs.permissions',
          effective: 'identity.users.detail.tabs.effective',
        },
        forceLogout: {
          label: 'identity.users.detail.forceLogout.label',
          confirmTitle: 'identity.users.detail.forceLogout.confirmTitle',
          confirmMessage: 'identity.users.detail.forceLogout.confirmMessage',
          confirmYes: 'identity.users.detail.forceLogout.confirmYes',
          confirmNo: 'identity.users.detail.forceLogout.confirmNo',
        },
        roles: {
          emptyMessage: 'identity.users.detail.roles.emptyMessage',
          columns: {
            role: 'identity.users.detail.roles.columns.role',
            grantedAt: 'identity.users.detail.roles.columns.grantedAt',
            expiresAt: 'identity.users.detail.roles.columns.expiresAt',
          },
          revokeConfirmTitle: 'identity.users.detail.roles.revokeConfirmTitle',
          revokeConfirmMessage: 'identity.users.detail.roles.revokeConfirmMessage',
          revokeConfirmYes: 'identity.users.detail.roles.revokeConfirmYes',
          revokeConfirmNo: 'identity.users.detail.roles.revokeConfirmNo',
        },
        permissions: {
          emptyMessage: 'identity.users.detail.permissions.emptyMessage',
          columns: {
            permissionCode: 'identity.users.detail.permissions.columns.permissionCode',
            reason: 'identity.users.detail.permissions.columns.reason',
            grantedAt: 'identity.users.detail.permissions.columns.grantedAt',
          },
          revokeConfirmTitle: 'identity.users.detail.permissions.revokeConfirmTitle',
          revokeConfirmMessage: 'identity.users.detail.permissions.revokeConfirmMessage',
          revokeConfirmYes: 'identity.users.detail.permissions.revokeConfirmYes',
          revokeConfirmNo: 'identity.users.detail.permissions.revokeConfirmNo',
        },
        effective: {
          hint: 'identity.users.detail.effective.hint',
          emptyMessage: 'identity.users.detail.effective.emptyMessage',
        },
      },
      commands: {
        assignRole: {
          label: 'identity.users.commands.assignRole.label',
          modalTitle: 'identity.users.commands.assignRole.modalTitle',
          roleLabel: 'identity.users.commands.assignRole.roleLabel',
          expiresAtLabel: 'identity.users.commands.assignRole.expiresAtLabel',
          expiresAtPlaceholder: 'identity.users.commands.assignRole.expiresAtPlaceholder',
          submitButton: 'identity.users.commands.assignRole.submitButton',
        },
        grantPermission: {
          label: 'identity.users.commands.grantPermission.label',
          modalTitle: 'identity.users.commands.grantPermission.modalTitle',
          permissionLabel: 'identity.users.commands.grantPermission.permissionLabel',
          reasonLabel: 'identity.users.commands.grantPermission.reasonLabel',
          reasonPlaceholder: 'identity.users.commands.grantPermission.reasonPlaceholder',
          submitButton: 'identity.users.commands.grantPermission.submitButton',
        },
      },
    },
    roles: {
      title: 'identity.roles.title',
      subtitle: 'identity.roles.subtitle',
      table: {
        emptyMessage: 'identity.roles.table.emptyMessage',
        columns: {
          code: 'identity.roles.table.columns.code',
          name: 'identity.roles.table.columns.name',
          isSystem: 'identity.roles.table.columns.isSystem',
          permissionCount: 'identity.roles.table.columns.permissionCount',
          memberCount: 'identity.roles.table.columns.memberCount',
        },
      },
      detail: {
        emptySelection: 'identity.roles.detail.emptySelection',
        systemBadge: 'identity.roles.detail.systemBadge',
        tabs: {
          permissions: 'identity.roles.detail.tabs.permissions',
          members: 'identity.roles.detail.tabs.members',
          containers: 'identity.roles.detail.tabs.containers',
          holders: 'identity.roles.detail.tabs.holders',
        },
        permissions: {
          emptyMessage: 'identity.roles.detail.permissions.emptyMessage',
          removeConfirmTitle: 'identity.roles.detail.permissions.removeConfirmTitle',
          removeConfirmMessage: 'identity.roles.detail.permissions.removeConfirmMessage',
          removeConfirmYes: 'identity.roles.detail.permissions.removeConfirmYes',
          removeConfirmNo: 'identity.roles.detail.permissions.removeConfirmNo',
        },
        members: {
          emptyMessage: 'identity.roles.detail.members.emptyMessage',
          columns: {
            code: 'identity.roles.detail.members.columns.code',
            name: 'identity.roles.detail.members.columns.name',
          },
          removeConfirmTitle: 'identity.roles.detail.members.removeConfirmTitle',
          removeConfirmMessage: 'identity.roles.detail.members.removeConfirmMessage',
          removeConfirmYes: 'identity.roles.detail.members.removeConfirmYes',
          removeConfirmNo: 'identity.roles.detail.members.removeConfirmNo',
        },
        containers: {
          emptyMessage: 'identity.roles.detail.containers.emptyMessage',
          columns: {
            code: 'identity.roles.detail.containers.columns.code',
            name: 'identity.roles.detail.containers.columns.name',
          },
        },
        holders: {
          emptyMessage: 'identity.roles.detail.holders.emptyMessage',
          columns: {
            email: 'identity.roles.detail.holders.columns.email',
            displayName: 'identity.roles.detail.holders.columns.displayName',
          },
        },
      },
      commands: {
        create: {
          label: 'identity.roles.commands.create.label',
          modalTitle: 'identity.roles.commands.create.modalTitle',
          codeLabel: 'identity.roles.commands.create.codeLabel',
          codePlaceholder: 'identity.roles.commands.create.codePlaceholder',
          nameLabel: 'identity.roles.commands.create.nameLabel',
          namePlaceholder: 'identity.roles.commands.create.namePlaceholder',
          descriptionLabel: 'identity.roles.commands.create.descriptionLabel',
          descriptionPlaceholder: 'identity.roles.commands.create.descriptionPlaceholder',
          submitButton: 'identity.roles.commands.create.submitButton',
        },
        addPermission: {
          label: 'identity.roles.commands.addPermission.label',
          modalTitle: 'identity.roles.commands.addPermission.modalTitle',
          permissionLabel: 'identity.roles.commands.addPermission.permissionLabel',
          submitButton: 'identity.roles.commands.addPermission.submitButton',
        },
        addMember: {
          label: 'identity.roles.commands.addMember.label',
          modalTitle: 'identity.roles.commands.addMember.modalTitle',
          roleLabel: 'identity.roles.commands.addMember.roleLabel',
          submitButton: 'identity.roles.commands.addMember.submitButton',
        },
      },
    },
    permissions: {
      title: 'identity.permissions.title',
      subtitle: 'identity.permissions.subtitle',
      searchLabel: 'identity.permissions.searchLabel',
      emptyMessage: 'identity.permissions.emptyMessage',
      obsoleteBadge: 'identity.permissions.obsoleteBadge',
      holders: {
        hint: 'identity.permissions.holders.hint',
        emptySelection: 'identity.permissions.holders.emptySelection',
        emptyMessage: 'identity.permissions.holders.emptyMessage',
        columns: {
          email: 'identity.permissions.holders.columns.email',
          displayName: 'identity.permissions.holders.columns.displayName',
        },
      },
    },
  } as const;
