/**
 * Typesafe translation keys for the users scope.
 * Generated automatically from pl-PL.json.
 * Do not edit this file manually.
 */
export const USERS_KEYS = {
    title: 'users.title',
    subtitle: 'users.subtitle',
    filters: {
      email: {
        label: 'users.filters.email.label',
        placeholder: 'users.filters.email.placeholder',
      },
      kind: {
        label: 'users.filters.kind.label',
        human: 'users.filters.kind.human',
        service: 'users.filters.kind.service',
      },
    },
    table: {
      emptyMessage: 'users.table.emptyMessage',
      kindHuman: 'users.table.kindHuman',
      kindService: 'users.table.kindService',
      columns: {
        email: 'users.table.columns.email',
        displayName: 'users.table.columns.displayName',
        isActive: 'users.table.columns.isActive',
        roleCount: 'users.table.columns.roleCount',
        kind: 'users.table.columns.kind',
        description: 'users.table.columns.description',
      },
    },
    detail: {
      emptySelection: 'users.detail.emptySelection',
      statusActive: 'users.detail.statusActive',
      statusInactive: 'users.detail.statusInactive',
      tabs: {
        list: 'users.detail.tabs.list',
        roles: 'users.detail.tabs.roles',
        permissions: 'users.detail.tabs.permissions',
        effective: 'users.detail.tabs.effective',
      },
      execForceLogout: {
        label: 'users.detail.execForceLogout.label',
        confirmTitle: 'users.detail.execForceLogout.confirmTitle',
        confirmMessage: 'users.detail.execForceLogout.confirmMessage',
        confirmYes: 'users.detail.execForceLogout.confirmYes',
        confirmNo: 'users.detail.execForceLogout.confirmNo',
      },
      roles: {
        emptyMessage: 'users.detail.roles.emptyMessage',
        columns: {
          role: 'users.detail.roles.columns.role',
          grantedAt: 'users.detail.roles.columns.grantedAt',
          expiresAt: 'users.detail.roles.columns.expiresAt',
        },
        revokeAction: 'users.detail.roles.revokeAction',
        revokeConfirmTitle: 'users.detail.roles.revokeConfirmTitle',
        revokeConfirmMessage: 'users.detail.roles.revokeConfirmMessage',
        revokeConfirmYes: 'users.detail.roles.revokeConfirmYes',
        revokeConfirmNo: 'users.detail.roles.revokeConfirmNo',
      },
      permissions: {
        emptyMessage: 'users.detail.permissions.emptyMessage',
        columns: {
          permissionCode: 'users.detail.permissions.columns.permissionCode',
          reason: 'users.detail.permissions.columns.reason',
          grantedAt: 'users.detail.permissions.columns.grantedAt',
        },
        revokeConfirmTitle: 'users.detail.permissions.revokeConfirmTitle',
        revokeConfirmMessage: 'users.detail.permissions.revokeConfirmMessage',
        revokeConfirmYes: 'users.detail.permissions.revokeConfirmYes',
        revokeConfirmNo: 'users.detail.permissions.revokeConfirmNo',
        revokeAction: 'users.detail.permissions.revokeAction',
      },
      effective: {
        hint: 'users.detail.effective.hint',
        emptyMessage: 'users.detail.effective.emptyMessage',
        columns: {
          module: 'users.detail.effective.columns.module',
          code: 'users.detail.effective.columns.code',
        },
      },
      selectionScope: {
        resolving: 'users.detail.selectionScope.resolving',
        allTitle: 'users.detail.selectionScope.allTitle',
        previewTitle: 'users.detail.selectionScope.previewTitle',
        previewDescription: 'users.detail.selectionScope.previewDescription',
        rowSelectionUnavailable: 'users.detail.selectionScope.rowSelectionUnavailable',
      },
      columns: {
        user: 'users.detail.columns.user',
      },
    },
    commands: {
      addRole: {
        label: 'users.commands.addRole.label',
        modalTitle: 'users.commands.addRole.modalTitle',
        roleLabel: 'users.commands.addRole.roleLabel',
        expiresAtLabel: 'users.commands.addRole.expiresAtLabel',
        expiresAtPlaceholder: 'users.commands.addRole.expiresAtPlaceholder',
        submitButton: 'users.commands.addRole.submitButton',
        editMessage: 'users.commands.addRole.editMessage',
        userSuffixSingle: 'users.commands.addRole.userSuffixSingle',
        userSuffixPlural: 'users.commands.addRole.userSuffixPlural',
        filterModeSuffix: 'users.commands.addRole.filterModeSuffix',
        filterModeHint: 'users.commands.addRole.filterModeHint',
      },
      addPermission: {
        label: 'users.commands.addPermission.label',
        modalTitle: 'users.commands.addPermission.modalTitle',
        permissionLabel: 'users.commands.addPermission.permissionLabel',
        reasonLabel: 'users.commands.addPermission.reasonLabel',
        reasonPlaceholder: 'users.commands.addPermission.reasonPlaceholder',
        submitButton: 'users.commands.addPermission.submitButton',
        editMessage: 'users.commands.addPermission.editMessage',
        userSuffixSingle: 'users.commands.addPermission.userSuffixSingle',
        userSuffixPlural: 'users.commands.addPermission.userSuffixPlural',
        filterModeSuffix: 'users.commands.addPermission.filterModeSuffix',
        filterModeHint: 'users.commands.addPermission.filterModeHint',
      },
      createIntegrationClient: {
        label: 'users.commands.createIntegrationClient.label',
        modalTitle: 'users.commands.createIntegrationClient.modalTitle',
        uuidLabel: 'users.commands.createIntegrationClient.uuidLabel',
        uuidPlaceholder: 'users.commands.createIntegrationClient.uuidPlaceholder',
        nameLabel: 'users.commands.createIntegrationClient.nameLabel',
        namePlaceholder: 'users.commands.createIntegrationClient.namePlaceholder',
        descriptionLabel: 'users.commands.createIntegrationClient.descriptionLabel',
        descriptionPlaceholder: 'users.commands.createIntegrationClient.descriptionPlaceholder',
        submitButton: 'users.commands.createIntegrationClient.submitButton',
      },
    },
  } as const;
