// <auto-generated />
using System;
using Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identity.Domain.Audit.GrantAuditEntry", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("subject_type");

                    b.Property<Guid>("SubjectUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_uuid");

                    b.Property<string>("TargetCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("target_code");

                    b.HasKey("Uuid")
                        .HasName("pk_grant_audit");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_grant_audit_occurred_at");

                    b.HasIndex("SubjectUuid")
                        .HasDatabaseName("ix_grant_audit_subject_uuid");

                    b.ToTable("grant_audit", "identity");
                });

            modelBuilder.Entity("Identity.Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_role");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_role_code");

                    b.ToTable("role", "identity");
                });

            modelBuilder.Entity("Identity.Domain.Users.UserAccount", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Uuid")
                        .HasName("pk_user_account");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_account_email");

                    b.ToTable("user_account", "identity");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.PermissionCatalogEntry", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("DescriptionKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description_key");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_obsolete");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resource");

                    b.HasKey("Code")
                        .HasName("pk_permission_catalog");

                    b.ToTable("permission_catalog", "identity");
                });

            modelBuilder.Entity("Identity.Domain.Roles.Role", b =>
                {
                    b.OwnsMany("Identity.Domain.Roles.RoleMemberEntry", "_memberRoleUuids", b1 =>
                        {
                            b1.Property<Guid>("container_uuid")
                                .HasColumnType("uuid")
                                .HasColumnName("container_uuid");

                            b1.Property<Guid>("MemberRoleUuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("member_uuid");

                            b1.HasKey("container_uuid", "MemberRoleUuid")
                                .HasName("pk_role_member");

                            b1.HasIndex("MemberRoleUuid")
                                .HasDatabaseName("ix_role_member_member_uuid");

                            b1.ToTable("role_member", "identity");

                            b1.WithOwner()
                                .HasForeignKey("container_uuid")
                                .HasConstraintName("fk_role_member_role_container_uuid");
                        });

                    b.OwnsMany("Identity.Domain.Roles.RolePermissionEntry", "_permissions", b1 =>
                        {
                            b1.Property<Guid>("role_uuid")
                                .HasColumnType("uuid")
                                .HasColumnName("role_uuid");

                            b1.Property<string>("PermissionCode")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("permission_code");

                            b1.HasKey("role_uuid", "PermissionCode")
                                .HasName("pk_role_permission");

                            b1.ToTable("role_permission", "identity");

                            b1.WithOwner()
                                .HasForeignKey("role_uuid")
                                .HasConstraintName("fk_role_permission_role_role_uuid");
                        });

                    b.Navigation("_memberRoleUuids");

                    b.Navigation("_permissions");
                });

            modelBuilder.Entity("Identity.Domain.Users.UserAccount", b =>
                {
                    b.OwnsMany("Identity.Domain.Users.UserPermissionGrant", "PermissionGrants", b1 =>
                        {
                            b1.Property<Guid>("user_uuid")
                                .HasColumnType("uuid")
                                .HasColumnName("user_uuid");

                            b1.Property<string>("PermissionCode")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("permission_code");

                            b1.Property<DateTimeOffset>("GrantedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("granted_at");

                            b1.Property<string>("GrantedBy")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("granted_by");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("reason");

                            b1.HasKey("user_uuid", "PermissionCode")
                                .HasName("pk_user_permission");

                            b1.ToTable("user_permission", "identity");

                            b1.WithOwner()
                                .HasForeignKey("user_uuid")
                                .HasConstraintName("fk_user_permission_user_account_user_uuid");
                        });

                    b.OwnsMany("Identity.Domain.Users.UserRoleGrant", "RoleGrants", b1 =>
                        {
                            b1.Property<Guid>("user_uuid")
                                .HasColumnType("uuid")
                                .HasColumnName("user_uuid");

                            b1.Property<Guid>("RoleUuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("role_uuid");

                            b1.Property<DateTimeOffset?>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("expires_at");

                            b1.Property<DateTimeOffset>("GrantedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("granted_at");

                            b1.Property<string>("GrantedBy")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("granted_by");

                            b1.HasKey("user_uuid", "RoleUuid")
                                .HasName("pk_user_role");

                            b1.HasIndex("RoleUuid")
                                .HasDatabaseName("ix_user_role_role_uuid");

                            b1.ToTable("user_role", "identity");

                            b1.WithOwner()
                                .HasForeignKey("user_uuid")
                                .HasConstraintName("fk_user_role_user_account_user_uuid");
                        });

                    b.Navigation("PermissionGrants");

                    b.Navigation("RoleGrants");
                });
#pragma warning restore 612, 618
        }
    }
}
