//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.0.0 (NJsonSchema v11.6.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

export interface IIdentityClient {
    /**
     * @return OK
     */
    getUser(body: GetUserAccountRequest): Observable<UserAccountDto[]>;
    /**
     * Pozycje katalogu użytkowników po identyfikatorach
     * @return OK
     */
    getUserDirectory(body: GetUserDirectoryRequest): Observable<UserDirectoryDto[]>;
    /**
     * @return OK
     */
    searchUser(body: SearchUserAccountRequest): Observable<SearchResponse>;
    /**
     * Wyszukiwanie w katalogu użytkowników
     * @return OK
     */
    searchUserDirectory(body: SearchUserDirectoryRequest): Observable<SearchResponse>;
    /**
     * Seryjne bezpośrednie nadanie uprawnienia użytkownikom z obsługą błędów cząstkowych
     * @return OK
     */
    userAddPermissionMultipleCommand(body: BatchCommandOfUserAddPermissionCommandAndSearchUserAccountRequest): Observable<BatchResult>;
    /**
     * Seryjne nadanie roli użytkownikom z obsługą błędów cząstkowych
     * @return OK
     */
    userAddRoleMultipleCommand(body: BatchCommandOfUserAddRoleCommandAndSearchUserAccountRequest): Observable<BatchResult>;
    /**
     * Seryjne wymuszenie wylogowania z obsługą błędów cząstkowych
     * @return OK
     */
    userExecForceLogoutMultipleCommand(body: BatchCommandOfUserExecForceLogoutCommandAndSearchUserAccountRequest): Observable<BatchResult>;
    /**
     * Seryjne odebranie bezpośrednio nadanego uprawnienia z obsługą błędów cząstkowych
     * @return OK
     */
    userRemovePermissionMultipleCommand(body: BatchCommandOfUserRemovePermissionCommandAndSearchUserAccountRequest): Observable<BatchResult>;
    /**
     * Seryjne odebranie roli użytkownikom z obsługą błędów cząstkowych
     * @return OK
     */
    userRemoveRoleMultipleCommand(body: BatchCommandOfUserRemoveRoleCommandAndSearchUserAccountRequest): Observable<BatchResult>;
    /**
     * @return OK
     */
    getRole(body: GetRoleRequest): Observable<RoleDto[]>;
    /**
     * @return OK
     */
    searchRole(body: SearchRoleRequest): Observable<SearchResponse>;
    /**
     * Seryjne dołączenie roli składowej z obsługą błędów cząstkowych
     * @return OK
     */
    roleAddMemberMultipleCommand(body: BatchCommandOfRoleAddMemberCommandAndSearchRoleRequest): Observable<BatchResult>;
    /**
     * Seryjne dodanie uprawnienia rolom z obsługą błędów cząstkowych
     * @return OK
     */
    roleAddPermissionMultipleCommand(body: BatchCommandOfRoleAddPermissionCommandAndSearchRoleRequest): Observable<BatchResult>;
    /**
     * Seryjne zakładanie ról z obsługą błędów cząstkowych
     * @return OK
     */
    roleCreateMultipleCommand(body: BatchCommandOfRoleCreateCommandAndSearchRoleRequest): Observable<BatchResult>;
    /**
     * Seryjne odłączenie roli składowej z obsługą błędów cząstkowych
     * @return OK
     */
    roleRemoveMemberMultipleCommand(body: BatchCommandOfRoleRemoveMemberCommandAndSearchRoleRequest): Observable<BatchResult>;
    /**
     * Seryjne odebranie uprawnienia rolom z obsługą błędów cząstkowych
     * @return OK
     */
    roleRemovePermissionMultipleCommand(body: BatchCommandOfRoleRemovePermissionCommandAndSearchRoleRequest): Observable<BatchResult>;
    /**
     * @return OK
     */
    searchPermissionCatalog(): Observable<PermissionCatalogEntryDto[]>;
    /**
     * @return OK
     */
    getMyPermissions(): Observable<string[]>;
    /**
     * @return OK
     */
    getMyPermissionSources(): Observable<EffectivePermissionSourceDto[]>;
    /**
     * @return OK
     */
    jobCancel(body: JobControlRequest): Observable<JobCancelResult>;
    /**
     * @return OK
     */
    jobRetryFailed(body: JobControlRequest): Observable<JobRetryFailedResult>;
    /**
     * @return OK
     */
    getUserPermissions(id: string): Observable<string[]>;
    /**
     * Seryjna rejestracja kont serwisowych (kluczy integracyjnych)
     * @return OK
     */
    integrationClientCreateMultipleCommand(body: BatchCommandOfIntegrationClientCreateCommandAndSearchUserAccountRequest): Observable<BatchResult>;
    /**
     * @return OK
     */
    getGrantAudit(body: GetGrantAuditRequest): Observable<GrantAuditDto[]>;
    /**
     * @return OK
     */
    searchGrantAudit(body: SearchGrantAuditRequest): Observable<SearchResponse>;
}

@Injectable({
    providedIn: 'root'
})
export class IdentityClient implements IIdentityClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "http://localhost:5280/";
    }

    /**
     * @return OK
     */
    getUser(body: GetUserAccountRequest): Observable<UserAccountDto[]> {
        let url_ = this.baseUrl + "/user/getUser";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetUser(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetUser(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<UserAccountDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<UserAccountDto[]>;
        }));
    }

    protected processGetUser(response: HttpResponseBase): Observable<UserAccountDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as UserAccountDto[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Pozycje katalogu użytkowników po identyfikatorach
     * @return OK
     */
    getUserDirectory(body: GetUserDirectoryRequest): Observable<UserDirectoryDto[]> {
        let url_ = this.baseUrl + "/user/getUserDirectory";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetUserDirectory(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetUserDirectory(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<UserDirectoryDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<UserDirectoryDto[]>;
        }));
    }

    protected processGetUserDirectory(response: HttpResponseBase): Observable<UserDirectoryDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as UserDirectoryDto[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    searchUser(body: SearchUserAccountRequest): Observable<SearchResponse> {
        let url_ = this.baseUrl + "/user/searchUser";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearchUser(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearchUser(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SearchResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SearchResponse>;
        }));
    }

    protected processSearchUser(response: HttpResponseBase): Observable<SearchResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SearchResponse;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Wyszukiwanie w katalogu użytkowników
     * @return OK
     */
    searchUserDirectory(body: SearchUserDirectoryRequest): Observable<SearchResponse> {
        let url_ = this.baseUrl + "/user/searchUserDirectory";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearchUserDirectory(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearchUserDirectory(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SearchResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SearchResponse>;
        }));
    }

    protected processSearchUserDirectory(response: HttpResponseBase): Observable<SearchResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SearchResponse;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjne bezpośrednie nadanie uprawnienia użytkownikom z obsługą błędów cząstkowych
     * @return OK
     */
    userAddPermissionMultipleCommand(body: BatchCommandOfUserAddPermissionCommandAndSearchUserAccountRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/user/batch-add-permission";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUserAddPermissionMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUserAddPermissionMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processUserAddPermissionMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjne nadanie roli użytkownikom z obsługą błędów cząstkowych
     * @return OK
     */
    userAddRoleMultipleCommand(body: BatchCommandOfUserAddRoleCommandAndSearchUserAccountRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/user/batch-add-role";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUserAddRoleMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUserAddRoleMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processUserAddRoleMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjne wymuszenie wylogowania z obsługą błędów cząstkowych
     * @return OK
     */
    userExecForceLogoutMultipleCommand(body: BatchCommandOfUserExecForceLogoutCommandAndSearchUserAccountRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/user/batch-exec-force-logout";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUserExecForceLogoutMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUserExecForceLogoutMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processUserExecForceLogoutMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjne odebranie bezpośrednio nadanego uprawnienia z obsługą błędów cząstkowych
     * @return OK
     */
    userRemovePermissionMultipleCommand(body: BatchCommandOfUserRemovePermissionCommandAndSearchUserAccountRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/user/batch-remove-permission";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUserRemovePermissionMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUserRemovePermissionMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processUserRemovePermissionMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjne odebranie roli użytkownikom z obsługą błędów cząstkowych
     * @return OK
     */
    userRemoveRoleMultipleCommand(body: BatchCommandOfUserRemoveRoleCommandAndSearchUserAccountRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/user/batch-remove-role";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUserRemoveRoleMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUserRemoveRoleMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processUserRemoveRoleMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getRole(body: GetRoleRequest): Observable<RoleDto[]> {
        let url_ = this.baseUrl + "/role/getRole";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetRole(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetRole(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<RoleDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<RoleDto[]>;
        }));
    }

    protected processGetRole(response: HttpResponseBase): Observable<RoleDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as RoleDto[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    searchRole(body: SearchRoleRequest): Observable<SearchResponse> {
        let url_ = this.baseUrl + "/role/searchRole";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearchRole(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearchRole(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SearchResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SearchResponse>;
        }));
    }

    protected processSearchRole(response: HttpResponseBase): Observable<SearchResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SearchResponse;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjne dołączenie roli składowej z obsługą błędów cząstkowych
     * @return OK
     */
    roleAddMemberMultipleCommand(body: BatchCommandOfRoleAddMemberCommandAndSearchRoleRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/role/batch-add-member";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processRoleAddMemberMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRoleAddMemberMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processRoleAddMemberMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjne dodanie uprawnienia rolom z obsługą błędów cząstkowych
     * @return OK
     */
    roleAddPermissionMultipleCommand(body: BatchCommandOfRoleAddPermissionCommandAndSearchRoleRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/role/batch-add-permission";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processRoleAddPermissionMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRoleAddPermissionMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processRoleAddPermissionMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjne zakładanie ról z obsługą błędów cząstkowych
     * @return OK
     */
    roleCreateMultipleCommand(body: BatchCommandOfRoleCreateCommandAndSearchRoleRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/role/batch-create";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processRoleCreateMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRoleCreateMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processRoleCreateMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjne odłączenie roli składowej z obsługą błędów cząstkowych
     * @return OK
     */
    roleRemoveMemberMultipleCommand(body: BatchCommandOfRoleRemoveMemberCommandAndSearchRoleRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/role/batch-remove-member";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processRoleRemoveMemberMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRoleRemoveMemberMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processRoleRemoveMemberMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjne odebranie uprawnienia rolom z obsługą błędów cząstkowych
     * @return OK
     */
    roleRemovePermissionMultipleCommand(body: BatchCommandOfRoleRemovePermissionCommandAndSearchRoleRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/role/batch-remove-permission";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processRoleRemovePermissionMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRoleRemovePermissionMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processRoleRemovePermissionMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    searchPermissionCatalog(): Observable<PermissionCatalogEntryDto[]> {
        let url_ = this.baseUrl + "/permission/catalog";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearchPermissionCatalog(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearchPermissionCatalog(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<PermissionCatalogEntryDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<PermissionCatalogEntryDto[]>;
        }));
    }

    protected processSearchPermissionCatalog(response: HttpResponseBase): Observable<PermissionCatalogEntryDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as PermissionCatalogEntryDto[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getMyPermissions(): Observable<string[]> {
        let url_ = this.baseUrl + "/me/permissions";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetMyPermissions(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetMyPermissions(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<string[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<string[]>;
        }));
    }

    protected processGetMyPermissions(response: HttpResponseBase): Observable<string[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as string[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getMyPermissionSources(): Observable<EffectivePermissionSourceDto[]> {
        let url_ = this.baseUrl + "/me/permissions/sources";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetMyPermissionSources(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetMyPermissionSources(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<EffectivePermissionSourceDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<EffectivePermissionSourceDto[]>;
        }));
    }

    protected processGetMyPermissionSources(response: HttpResponseBase): Observable<EffectivePermissionSourceDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as EffectivePermissionSourceDto[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    jobCancel(body: JobControlRequest): Observable<JobCancelResult> {
        let url_ = this.baseUrl + "/job/cancel";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processJobCancel(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processJobCancel(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<JobCancelResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<JobCancelResult>;
        }));
    }

    protected processJobCancel(response: HttpResponseBase): Observable<JobCancelResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as JobCancelResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    jobRetryFailed(body: JobControlRequest): Observable<JobRetryFailedResult> {
        let url_ = this.baseUrl + "/job/retry-failed";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processJobRetryFailed(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processJobRetryFailed(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<JobRetryFailedResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<JobRetryFailedResult>;
        }));
    }

    protected processJobRetryFailed(response: HttpResponseBase): Observable<JobRetryFailedResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as JobRetryFailedResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getUserPermissions(id: string): Observable<string[]> {
        let url_ = this.baseUrl + "/internal/users/{Id}/permissions";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{Id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetUserPermissions(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetUserPermissions(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<string[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<string[]>;
        }));
    }

    protected processGetUserPermissions(response: HttpResponseBase): Observable<string[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as string[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Seryjna rejestracja kont serwisowych (kluczy integracyjnych)
     * @return OK
     */
    integrationClientCreateMultipleCommand(body: BatchCommandOfIntegrationClientCreateCommandAndSearchUserAccountRequest): Observable<BatchResult> {
        let url_ = this.baseUrl + "/integration-client/batch-create";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processIntegrationClientCreateMultipleCommand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processIntegrationClientCreateMultipleCommand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BatchResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BatchResult>;
        }));
    }

    protected processIntegrationClientCreateMultipleCommand(response: HttpResponseBase): Observable<BatchResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BatchResult;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Forbidden", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getGrantAudit(body: GetGrantAuditRequest): Observable<GrantAuditDto[]> {
        let url_ = this.baseUrl + "/grant-audit/getGrantAudit";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetGrantAudit(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetGrantAudit(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GrantAuditDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GrantAuditDto[]>;
        }));
    }

    protected processGetGrantAudit(response: HttpResponseBase): Observable<GrantAuditDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as GrantAuditDto[];
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    searchGrantAudit(body: SearchGrantAuditRequest): Observable<SearchResponse> {
        let url_ = this.baseUrl + "/grant-audit/search";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearchGrantAudit(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearchGrantAudit(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SearchResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SearchResponse>;
        }));
    }

    protected processSearchGrantAudit(response: HttpResponseBase): Observable<SearchResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SearchResponse;
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfIntegrationClientCreateCommandAndSearchUserAccountRequest {
    commands?: IntegrationClientCreateCommand[] | undefined;
    templateCommand?: IntegrationClientCreateCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchUserAccountRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfRoleAddMemberCommandAndSearchRoleRequest {
    commands?: RoleAddMemberCommand[] | undefined;
    templateCommand?: RoleAddMemberCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchRoleRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfRoleAddPermissionCommandAndSearchRoleRequest {
    commands?: RoleAddPermissionCommand[] | undefined;
    templateCommand?: RoleAddPermissionCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchRoleRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfRoleCreateCommandAndSearchRoleRequest {
    commands?: RoleCreateCommand[] | undefined;
    templateCommand?: RoleCreateCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchRoleRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfRoleRemoveMemberCommandAndSearchRoleRequest {
    commands?: RoleRemoveMemberCommand[] | undefined;
    templateCommand?: RoleRemoveMemberCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchRoleRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfRoleRemovePermissionCommandAndSearchRoleRequest {
    commands?: RoleRemovePermissionCommand[] | undefined;
    templateCommand?: RoleRemovePermissionCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchRoleRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfUserAddPermissionCommandAndSearchUserAccountRequest {
    commands?: UserAddPermissionCommand[] | undefined;
    templateCommand?: UserAddPermissionCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchUserAccountRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfUserAddRoleCommandAndSearchUserAccountRequest {
    commands?: UserAddRoleCommand[] | undefined;
    templateCommand?: UserAddRoleCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchUserAccountRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfUserExecForceLogoutCommandAndSearchUserAccountRequest {
    commands?: UserExecForceLogoutCommand[] | undefined;
    templateCommand?: UserExecForceLogoutCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchUserAccountRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfUserRemovePermissionCommandAndSearchUserAccountRequest {
    commands?: UserRemovePermissionCommand[] | undefined;
    templateCommand?: UserRemovePermissionCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchUserAccountRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

/** Żądanie operacji masowej: co wykonać (List&lt;TCommand&gt;? BatchCommand&lt;TCommand, TFilter&gt;.Commands albo TCommand? BatchCommand&lt;TCommand, TFilter&gt;.TemplateCommand) i na czym (List&lt;Guid&gt;? BatchCommand&lt;TCommand, TFilter&gt;.TargetUuids albo TFilter? BatchCommand&lt;TCommand, TFilter&gt;.TargetFilter) — patrz `BatchEndpointBase.ResolveTargetsAsync`. */
export interface BatchCommandOfUserRemoveRoleCommandAndSearchUserAccountRequest {
    commands?: UserRemoveRoleCommand[] | undefined;
    templateCommand?: UserRemoveRoleCommand | undefined;
    targetUuids?: string[] | undefined;
    targetFilter?: SearchUserAccountRequest | undefined;
    /** Identyfikator wywołującego — po stronie frontendu jest to identyfikator modalu, z którego
poszła operacja. Wraca w `JobDto.QueueId` i pozwala zgrupować powiadomienia
(„5 zadań z modalu zmiany ceny”) oraz otworzyć ten sam modal przy ponowieniu.

Backend traktuje wartość jako nieprzezroczystą etykietę — nigdy jej nie parsuje. */
    queueId?: string | undefined;
    /** Blob metadanych frontendu (klucz tłumaczenia komendy, kontekst modalu), przenoszony
bez zmian do `JobAccepted.UiMetadata` i dalej do repliki w Notification.

Istnieje, bo backend zna wyłącznie techniczną nazwę typu komendy
(`ProductSetPriceCommand`), a powiadomienie ma pokazać zdanie w języku użytkownika.
Tłumaczenie nazwy komendy na tekst jest wiedzą frontendu i tam zostaje — backend
przechowuje ją jako `jsonb`, którego nigdy nie interpretuje. */
    uiMetadata?: string | undefined;

    [key: string]: any;
}

export interface BatchResult {
    jobUuid?: string;

    [key: string]: any;
}

export interface EffectivePermissionSourceDto {
    permissionCode: string;
    sourceRoleUuid: string | undefined;
    sourceRoleCode: string | undefined;
    viaContainerRoleUuid: string | undefined;

    [key: string]: any;
}

export interface GetGrantAuditRequest {
    uuids?: string[] | undefined;

    [key: string]: any;
}

export interface GetRoleRequest {
    uuids?: string[] | undefined;

    [key: string]: any;
}

export interface GetUserAccountRequest {
    uuids?: string[] | undefined;

    [key: string]: any;
}

export interface GetUserDirectoryRequest {
    uuids?: string[] | undefined;

    [key: string]: any;
}

export interface GrantAuditDto {
    uuid: string;
    occurredAt: Date;
    actorUserUuid: string;
    subjectType: string;
    subjectUuid: string;
    action: string;
    targetCode: string;
    reason: string | undefined;
    source: string;

    [key: string]: any;
}

export interface IntegrationClientCreateCommand {
    uuid?: string;
    name?: string;
    description?: string | undefined;

    [key: string]: any;
}

/** Wynik anulowania — status zwrócony od razu, bez czekania na runner. */
export interface JobCancelResult {
    jobUuid?: string;
    status?: string;

    [key: string]: any;
}

/** Żądanie sterujące zadaniem masowym po jego identyfikatorze. */
export interface JobControlRequest {
    jobUuid?: string;

    [key: string]: any;
}

/** Wynik ponowienia — identyfikator nowo utworzonego zadania. */
export interface JobRetryFailedResult {
    newJobUuid?: string;

    [key: string]: any;
}

export interface PermissionCatalogEntryDto {
    code: string;
    module: string;
    resource: string;
    action: string;
    descriptionKey: string;
    isObsolete: boolean;

    [key: string]: any;
}

export interface RoleAddMemberCommand {
    uuid?: string;
    memberRoleUuid?: string;

    [key: string]: any;
}

export interface RoleAddPermissionCommand {
    uuid?: string;
    permissionCode?: string;

    [key: string]: any;
}

export interface RoleCreateCommand {
    uuid?: string;
    code?: string;
    name?: string;
    description?: string | undefined;

    [key: string]: any;
}

export interface RoleDto {
    uuid: string;
    code: string;
    name: string;
    description: string | undefined;
    isSystem: boolean;
    permissions: string[];
    memberRoleUuids: string[];

    [key: string]: any;
}

export interface RoleRemoveMemberCommand {
    uuid?: string;
    memberRoleUuid?: string;

    [key: string]: any;
}

export interface RoleRemovePermissionCommand {
    uuid?: string;
    permissionCode?: string;

    [key: string]: any;
}

export interface SearchGrantAuditRequest {
    subjectUuid?: string | undefined;
    subjectType?: string | undefined;
    action?: string | undefined;
    page?: number;
    pageSize?: number;
    sorts?: SortOption[] | undefined;

    [key: string]: any;
}

export interface SearchResponse {
    uuids?: string[];
    totalCount?: number;

    [key: string]: any;
}

export interface SearchRoleRequest {
    name?: string | undefined;
    page?: number;
    pageSize?: number;
    sorts?: SortOption[] | undefined;

    [key: string]: any;
}

export interface SearchUserAccountRequest {
    email?: string | undefined;
    roleUuid?: string | undefined;
    permissionCode?: string | undefined;
    kind?: number | undefined;
    page?: number;
    pageSize?: number;
    sorts?: SortOption[] | undefined;

    [key: string]: any;
}

export interface SearchUserDirectoryRequest {
    query?: string | undefined;
    includeInactive?: boolean;
    page?: number;
    pageSize?: number;
    sorts?: SortOption[] | undefined;

    [key: string]: any;
}

export interface SortOption {
    field?: string;
    order?: number;

    [key: string]: any;
}

export interface UserAccountDto {
    uuid: string;
    email: string;
    displayName: string;
    isActive: boolean;
    kind: number;
    description: string | undefined;
    roleGrants: UserRoleGrantDto[];
    permissionGrants: UserPermissionGrantDto[];

    [key: string]: any;
}

export interface UserAddPermissionCommand {
    uuid?: string;
    permissionCode?: string;
    reason?: string;

    [key: string]: any;
}

export interface UserAddRoleCommand {
    uuid?: string;
    roleUuid?: string;
    expiresAt?: Date | undefined;

    [key: string]: any;
}

export interface UserDirectoryDto {
    uuid: string;
    displayName: string;
    email: string;
    isActive: boolean;

    [key: string]: any;
}

export interface UserExecForceLogoutCommand {
    uuid?: string;

    [key: string]: any;
}

export interface UserPermissionGrantDto {
    permissionCode: string;
    grantedAt: Date;
    grantedBy: string | undefined;
    reason: string;

    [key: string]: any;
}

export interface UserRemovePermissionCommand {
    uuid?: string;
    permissionCode?: string;

    [key: string]: any;
}

export interface UserRemoveRoleCommand {
    uuid?: string;
    roleUuid?: string;

    [key: string]: any;
}

export interface UserRoleGrantDto {
    roleUuid: string;
    grantedAt: Date;
    grantedBy: string | undefined;
    expiresAt: Date | undefined;

    [key: string]: any;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}