/**
 * Typesafe translation keys for the permissions scope.
 * Generated automatically from pl-PL.json.
 * Do not edit this file manually.
 */
export const PERMISSIONS_KEYS = {
  title: 'permissions.title',
  subtitle: 'permissions.subtitle',
  searchLabel: 'permissions.searchLabel',
  emptyMessage: 'permissions.emptyMessage',
  obsoleteBadge: 'permissions.obsoleteBadge',
  holders: {
    hint: 'permissions.holders.hint',
    emptySelection: 'permissions.holders.emptySelection',
    emptyMessage: 'permissions.holders.emptyMessage',
    columns: {
      email: 'permissions.holders.columns.email',
      displayName: 'permissions.holders.columns.displayName',
    },
  },
} as const;
